name: Push
on:
  push:
    branches:
      - main

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
      - name: Setup GPG keys
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" >> ~/secret-key.asc
          chmod 600 ~/secret-key.asc
      - name: Deploy to Maven Central
        run: |
          ./gradlew publishToMavenCentral \
            -Psigning.secretKeyRingFile="$HOME/secret-key.asc" \
            -PmavenCentralUsername="${{ secrets.MAVEN_CENTREAL_PORTAL_USERNAME }}" \
            -PmavenCentralPassword="${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}"
        env:
          RELEASE_VERSION: 0.1.0-SNAPSHOT
